### ISSUE TITLE
[210909] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#101]
### Daliy Achievement Goals
* `10시 ~ 12시` JS 프로젝트 리팩토링 - 1
* `13시 ~ 18시` JS 프로젝트 리팩토링 - 2
* `19시 ~ 24시` JS 프로젝트 리팩토링 - 3

### TODO
- [x] JS 프로젝트 리팩토링 - 1
- [x] JS 프로젝트 리팩토링 - 2
- [x] JS 프로젝트 리팩토링 - 3
