### ISSUE TITLE
[210916] 이우성

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#108]
### Daliy Achievement Goals
* `10시 ~ 12시` geeksforgeeks 알고리즘 풀기
* `13시 ~ 18시` geeksforgeeks 알고리즘 풀기
* `19시 ~ 23시` Vanilla JS 리팩토링

### TODO
- [x] geeksforgeeks - Minimum Increment operations to make Array unique
- [x] geeksforgeeks - Minimum Increment / decrement to make array elements equal  
- [x] geeksforgeeks - Minimum sum of two numbers formed from digits of an array
- [x] geeksforgeeks - Minimum operations to make GCD of array a multiple of k
- [x] geeksforgeeks - Minimum sum of absolute difference of pairs of two arrays
- [x] geeksforgeeks - Making elements of two arrays same with minimum increment/decrement
- [x] geeksforgeeks - Sorting array with reverse around middle
- [x] Vanilla JS 리팩토링

### Repositories
[JS portfolio-web Repo](https://github.com/useonglee/portfolio-web)
[geeksforgeeks Repo](https://github.com/useonglee/algorithm/tree/master/geeksforgeeks)
