### ISSUE TITLE
[210917] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#109]
### Daliy Achievement Goals
* `09시 ~ 12시` testdome JS 알고리즘 풀기
* `13시 ~ 18시` LintCode 알고리즘 풀기
* `19시 ~ 23시` LintCode 알고리즘 풀기

### TODO

**TestDome**
- [x] testdome - JS: Ensure
- [x] testdome - JS: Even Numbers
- [x] testdome - JS: Remove Property
- [x] testdome - JS: Date
- [x] testdome - JS: Image Gallery
- [x] testdome - JS: Check Digit
- [x] testdome - JS: Closures
- [x] testdome - JS: Loop

**LintCode**
- [x] LintCode - 1476
- [x] LintCode - 1451
- [x] LintCode - 1438
- [x] LintCode - 1425
- [x] LintCode - 1314
- [x] LintCode - 1294
- [ ] LintCode - 1282
- [ ] LintCode - 1226
- [ ] LintCode - 1256
- [ ] LintCode - 1237
- [ ] LintCode - 1236

### Repositories
[TestDome Repo](https://github.com/useonglee/algorithm/tree/master/TestDome)
[LintCode Repo](https://github.com/useonglee/algorithm/tree/master/LintCode)
