### ISSUE TITLE
[210924] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#114]
### Daliy Achievement Goals
* `10시 ~ 12시` GeeksforGeeks 알고리즘 복습
* `13시 ~ 18시` Codility 알고리즘 풀기
* `19시 ~ 24시` TestDome JS 알고리즘 풀기

### TODO
**GeeksforGeeks 알고리즘 복습 문제**
- [x] geeksforgeeks - Minimum Increment operations to make Array unique
- [x] geeksforgeeks - Minimum Increment / decrement to make array elements equal  
- [x] geeksforgeeks - Minimum sum of two numbers formed from digits of an array
- [x] geeksforgeeks - Minimum operations to make GCD of array a multiple of k
- [x] geeksforgeeks - Minimum sum of absolute difference of pairs of two arrays
- [x] geeksforgeeks - Making elements of two arrays same with minimum increment/decrement
- [x] geeksforgeeks - Sorting array with reverse around middle

**Codility**
- [x] Codility - Exercise 5: ParityDegree
- [x] Codility - Exercise 5: ThreeLetters
- [x] Codility - Exercise 4: FirstUnique
- [x] Codility - Exercise 4: StrSymmetryPoint
- [x] Codility - Exercise 4: TreeHeight

**TestDome**
- [x] TestDome - JS: Song
- [x] TestDome - JS: Topic Coloring
- [x] TestDome - JS: Two Sum
- [x] TestDome - JS: Endangered Species

### Repositories
[geeksforgeeks Repo](https://github.com/useonglee/algorithm/tree/master/geeksforgeeks)
[Codility Repo](https://github.com/useonglee/algorithm/tree/master/Codility)
[TestDome Repo](https://github.com/useonglee/algorithm/tree/master/TestDome)
