### ISSUE TITLE
[210925] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#115]
### Daliy Achievement Goals
* `11시 ~ 12시` TestDome JS 알고리즘 풀기
* `13시 ~ 17시` TestDome JS 알고리즘 풀기
* `19시 ~ 24시` TestDome JS 알고리즘 풀기

### TODO
**TestDome**
- [x] TestDome - JS: Endangered Species
- [x] TestDome - JS: Food Ranking
- [x] TestDome - JS: Closest Relative
- [x] TestDome - JS: Customer List

### Repositories
[TestDome Repo](https://github.com/useonglee/algorithm/tree/master/TestDome)
