### ISSUE TITLE
[210926] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#116]
### Daliy Achievement Goals
* `09시 ~ 12시` Codility 알고리즘 풀기
* `13시 ~ 18시` Codility 알고리즘 풀기
* `19시 ~ 24시` Codility 알고리즘 풀기

### TODO
**Codility**
- [x] Codility - Exercise 7: ArrListLen
- [x] Codility - Exercise 4: ArrayInversionCount
- [x] Codility - Exercise 3: TennisTournament
- [x] Codility - Exercise 3: SocksLaundering
- [x] Codility - Exercise 1: LongestPassword
- [x] Codility - Lesson 4: MaxCounters
- [x] Codility - Lesson 7: Fish
- [ ] Codility - Lesson 8: EquiLeader
- [ ] Codility - Lesson 9: MaxProfit
- [ ] Codility - Lesson 9: MaxSliceSum

### Repositories
[Codility Repo](https://github.com/useonglee/algorithm/tree/master/Codility)
