### ISSUE TITLE
[210927] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#117]
### Daliy Achievement Goals
* `10시 ~ 12시` Codility 알고리즘 풀기
* `13시 ~ 18시` Codility 알고리즘 풀기
* `19시 ~ 20시` TestDome JS 알고리즘 복습
* `20시 ~ 24시` LintCode 알고리즘 복습

### TODO
**Codility**
- [x] Codility - Lesson 8: EquiLeader
- [x] Codility - Lesson 9: MaxProfit
- [x] Codility - Lesson 9: MaxSliceSum
- [x] Codility - Exercise 3: SocksLaundering

**TestDome JS**
- [x] TestDome - JS: Image Gallery
- [x] TestDome - JS: Topic Coloring
- [x] TestDome - JS: Endangered Species
- [x] TestDome - JS: Food Ranking
- [x] TestDome - JS: Closest Relative
- [x] TestDome - JS: Customer List

**LintCode**
- [x] LintCode - 828
- [x] LintCode - 1859
- [x] LintCode - 1510
- [x] LintCode - 1476
- [x] LintCode - 1451
- [x] LintCode - 1821
- [x] LintCode - 1819

### Repositories
[Codility Repo](https://github.com/useonglee/algorithm/tree/master/Codility)
[TestDome Repo](https://github.com/useonglee/algorithm/tree/master/TestDome)
[LintCode Repo](https://github.com/useonglee/algorithm/tree/master/LintCode)
