### ISSUE TITLE
[210728] 김주혜 계획

### ISSUE THREAD

**Issue by Juhye-Kim** [Drunken-Growth/TIL#12]
### 목표
- 미션

### TODO
> 함수형 프로그래밍
- [x] 구현1 `12~12AM`
- [x] 구현2 `12~12AM`
- [x] 개선
  - 함수합성 활용
  - 커링 활용
- [x] 해설영상
- [x] 체크포인트 `~12AM`

**리팩토링 자바스크립트**
- [x] 11장. 함수형 프로그래밍

### 더 공부하기
- [ ] [enum](https://www.sohamkamani.com/javascript/enums/)
- [ ] [Symbol](https://feel5ny.github.io/2019/02/03/JS_23/)
- [ ] [SOLID](https://www.nextree.co.kr/p6960/)
- [ ] [OOP](https://techblog.woowahan.com/2502/)
