### ISSUE TITLE
[210726] 김주혜 계획

### ISSUE THREAD

**Issue by Juhye-Kim** [Drunken-Growth/TIL#2]
### 목표
- 미션
- Flutter 공부
- Javascript 개인공부

### TODO
> XML 파서 구현, XPath 탐색
- [x] 미션1 `12~7PM`
- [x] 미션2 `12~7PM`
- [x] 해설강의
- [x] 체크포인트 `~12AM`

Flutter
- [ ] [Dart언어](https://www.youtube.com/watch?v=2g8DsOSreqk)

### 공부할 주제
- [x] 컴파일러 이론
- [x] tokenizer, lexer, parser 역할
- [x] token 종류 (identifier, keyword, operator, literal, comment)
- [x] js 예외 처리
- [x] babel handbook
