### ISSUE TITLE
[210729] 김주혜 계획

### ISSUE THREAD

**Issue by Juhye-Kim** [Drunken-Growth/TIL#21]
### TODO
> 버전관리시스템
- [x] 구현1 `12~12AM`
- [x] 구현2 `12~12AM`
- [ ] 해설영상
- [x] 체크포인트 `~12AM`
- [ ] 어제꺼 - 리팩토링
  - 출력부분 합성함수로 구현해보기

### 더 공부하기
- [x] fs모듈
- [x] [git](http://rogerdudler.github.io/git-guide/index.ko.html)
- [x] git 객체, 내부 동작원리
- [x] [버전관리 시스템](https://git-scm.com/book/ko/v2/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-%EB%B2%84%EC%A0%84-%EA%B4%80%EB%A6%AC%EB%9E%80%3F)
- [x] [git 파일 상태변화](https://git-scm.com/book/ko/v2/Git%EC%9D%98-%EA%B8%B0%EC%B4%88-%EC%88%98%EC%A0%95%ED%95%98%EA%B3%A0-%EC%A0%80%EC%9E%A5%EC%86%8C%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0)
- [ ] [enum](https://www.sohamkamani.com/javascript/enums/)
- [ ] [Symbol](https://feel5ny.github.io/2019/02/03/JS_23/)
- [ ] [SOLID](https://www.nextree.co.kr/p6960/)
- [ ] [OOP](https://techblog.woowahan.com/2502/)
