### ISSUE TITLE
[210730] 김주혜 계획

### ISSUE THREAD

**Issue by Juhye-Kim** [Drunken-Growth/TIL#26]
### TODO
- [ ] 어제꺼 해설영상
- [x] 플러터
  - [x] [install, setting](https://puzzle-puzzle.tistory.com/entry/Flutter-%ED%94%8C%EB%9F%AC%ED%84%B0-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0-Install-Flutter-for-Mac)
    - [x] [이전버전 12.4](https://developer.apple.com/download/all/) 
  - [x] [공식문서](https://flutter-ko.dev/docs/get-started/codelab)
- [x] [파이어베이스]

### 더 공부하기
- [ ] [enum](https://www.sohamkamani.com/javascript/enums/)
- [ ] [Symbol](https://feel5ny.github.io/2019/02/03/JS_23/)
- [ ] [SOLID](https://www.nextree.co.kr/p6960/)
- [ ] [OOP](https://techblog.woowahan.com/2502/)
