### ISSUE TITLE
[210726] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#4]
### Daliy Achievement Goals
* `a.m 09 ~ 12` 네트워크
* `p.m 13 ~ 18` JS 과제
* `p.m 19 ~ 23` 자율 학습

### TODO
- [x] 네트워크 강의 듣기
- [x] Javascript 과제 정하기
- [x] 프로그래머스 - 다음 큰 숫자
- [x] 프로그래머스 - 숫자의 표현
