### ISSUE TITLE
[210727] 김주혜 계획

### ISSUE THREAD

**Issue by Juhye-Kim** [Drunken-Growth/TIL#6]
### 목표
- 미션
- OOP 마스터

### TODO
> 체스게임 구현, OOP
- [x] 구현 `12~12AM`
- [x] 해설영상
- [x] 체크포인트 `~12AM`

**You don't know JS**
- [x] Chapter 4. 클래스와 객체의 혼합
- [x] Chapter 5. Prototype

**자바스크립트 파워북**
- [x] 3장. 객체와 클래스

### 더 공부할 주제
- [x] this
- [ ] [enum](https://www.sohamkamani.com/javascript/enums/)
- [x] readline 모듈 - 반복입력받기
- [x] [유니코드 이스케이프](https://tyboss.tistory.com/entry/Javascript-%EC%9C%A0%EB%8B%88%EC%BD%94%EB%93%9C-Unicode-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0)
