### ISSUE TITLE
[210816] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#70]
### Daliy Achievement Goals
* `10시 ~ 12시` 코딜리티 문제 풀기
* `13시 ~ 16시` 코딜리티 문제 풀기
* `16시 ~ 18시` JS 심화 공부
* `19시 ~ 23시` 코딜리티 문제 풀기

### TODO
- [x] 오전 코딜리티 문제 풀기
- [x] 오후 코딜리티 문제 풀기
- [x] JS 심화 공부
- [x] 오후 코딜리티 문제 풀기
