### ISSUE TITLE
[210817] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#72]
### Daliy Achievement Goals
* `09시 ~ 12시` 토이 알고리즘 풀기
* `14시 ~ 15시` JS 심화 학습
* `17시 ~ 18시` JS 심화 모의 면접
* `19시 ~ 21시` 코딩테스트
* `21시 ~ 23시` JS 심화 학습 블로깅

### TODO
- [x] 토이 알고리즘 풀기
- [x] JS 심화 학습
- [x] JS 심화 모의 면접
- [x] 코딩테스트
- [x] JS 심화 학습 블로깅

**Comment by Outwater** [comment]
우성님 화이팅입니다!! 저는 게을러서..task작성을 못하였지만 ㅠ.ㅠ
