### ISSUE TITLE
[210902] 이우성 계획

### ISSUE THREAD

**Issue by useonglee** [Drunken-Growth/TIL#96]
### Daliy Achievement Goals
* `09시 ~ 11시` 토이 알고리즘 풀기
* `11시 ~ 12시` 라이브 코딩 준비
* `13시 ~ 16시` 모의 라이브 코딩 테스트
* `16시 ~ 18시` 프로젝트 블로깅
* `19시 ~ 22시` 프로젝트 개선
* `22시 ~ 24시` 모의 면접 준비

### TODO
- [x] 토이 알고리즘 풀기
- [x] 라이브 코딩준비
- [x] 모의 라이브 코딩 테스트
- [x] 프로젝트 블로깅
- [x] 프로젝트 개선
- [x] 모의 면접 준비
